import { createContext, useContext, useEffect, useState, type ReactNode } from "react";

export type Lang = "en" | "th";
export type Theme = "light" | "dark";

type Settings = {
  theme: Theme;
  fontScale: number;
  lang: Lang;
  setTheme: (t: Theme) => void;
  toggleTheme: () => void;
  setFontScale: (n: number) => void;
  setLang: (l: Lang) => void;
  t: (key: TKey) => string;
};

const dictionaries = {
  en: {
    "app.name": "Fall Guard",
    "app.tagline": "Fall Risk AI",
    "nav.monitoring": "Monitoring",
    "nav.dashboard": "Dashboard",
    "nav.patients": "Patients",
    "nav.anomalies": "Anomaly Logs",
    "nav.settings": "Settings",
    "header.search": "Search patients, devices, events…",
    "header.notifications": "Notifications",
    "header.role": "Caregiver",
    "a11y.theme": "Toggle theme",
    "a11y.fontSmaller": "Decrease text size",
    "a11y.fontReset": "Reset text size",
    "a11y.fontLarger": "Increase text size",
    "a11y.language": "Change language",
    "dashboard.title": "Global Overview",
    "dashboard.subtitle": "Real-time monitoring across {n} patients · updated continuously",
    "dashboard.managePatients": "Manage patients",
    "kpi.atRisk": "Patients At Risk",
    "kpi.atRisk.hint": "Live · requires attention",
    "kpi.alertsToday": "Total Risk Alerts Today",
    "kpi.alertsToday.hint": "+15% vs last week",
    "kpi.monitored": "Monitored Patients",
    "kpi.monitored.hint": "2 stable improvements",
    "kpi.uptime": "Device Uptime",
    "kpi.uptime.hint": "Across 8 wearables",
    "chart.trends.title": "Fall-Risk Event Trends",
    "chart.trends.desc": "AI-predicted risk vs. normal motion events across all patients.",
    "chart.byHour.title": "Risk by Time of Day",
    "chart.byHour.desc": "Most alerts cluster around night hours.",
    "range.daily": "Daily",
    "range.weekly": "Weekly",
    "range.monthly": "Monthly",
    "range.yearly": "Yearly",
    "roster.title": "Patient Roster",
    "roster.desc": "Live status from each connected wearable.",
    "patient.device": "Device",
    "patient.lastUpdate": "Last update",
    "patient.monitor": "Monitor",
    "status.normal": "Normal",
    "status.risk": "Risk",
    "patients.title": "Patients Overview",
    "patients.subtitle": "Add, edit and manage monitored patients and their devices.",
    "patients.add": "Add Patient",
    "patients.edit": "Edit Patient",
    "patients.addNew": "Add New Patient",
    "patients.editDesc": "Update profile and device info.",
    "patients.addDesc": "Register a new patient and link their wearable device.",
    "field.name": "Full name",
    "field.age": "Age",
    "field.gender": "Gender",
    "field.weight": "Weight (kg)",
    "field.height": "Height (cm)",
    "field.deviceId": "Device ID",
    "field.room": "Address",
    "gender.female": "Female",
    "gender.male": "Male",
    "action.cancel": "Cancel",
    "action.save": "Save changes",
    "action.addPatient": "Add patient",
    "col.patient": "Patient",
    "col.age": "Age",
    "col.gender": "Gender",
    "col.bmi": "BMI",
    "col.device": "Device",
    "col.room": "Address",
    "col.status": "Status",
    "col.actions": "Actions",
    "col.date": "Date",
    "col.time": "Time",
    "col.event": "Event Type",
    "col.accel": "Accel (g)",
    "col.gyro": "Gyro (°/s)",
    "col.severity": "Severity",
    "anomalies.title": "Abnormal Events Log",
    "anomalies.subtitle": "All abnormal events detected across monitored patients.",
    "anomalies.export": "Export CSV",
    "anomalies.filters": "Filters",
    "anomalies.filtersDesc": "Search by patient, filter by event type or severity.",
    "anomalies.search": "Search patient name…",
    "anomalies.allTypes": "All event types",
    "anomalies.allSeverities": "All severities",
    "anomalies.noResults": "No events match your filters.",
    "severity.high": "High",
    "severity.medium": "Medium",
    "severity.low": "Low",
    "patient.back": "Patients",
    "patient.aiPrediction": "Current AI Prediction",
    "patient.fallRisk": "Fall Risk Detected",
    "patient.normalActivity": "Normal Activity",
    "patient.confidence": "Confidence",
    "patient.model": "model",
    "patient.realtime.accel": "Accelerometer",
    "patient.realtime.gyro": "Gyroscope",
    "patient.realtime.live": "Live",
    "patient.trend.title": "Personal Risk Trend",
    "patient.trend.desc": "Risk occurred {n} times this week, mostly during night hours.",
    "patient.time.night": "Night (10pm–6am)",
    "patient.time.day": "Daytime",
    "patient.logs.title": "Recent Anomaly Logs",
    "patient.logs.desc": "Events recorded for this patient.",
    "lang.short.en": "EN",
    "lang.short.th": "ไทย",
    "index.searchPlaceholder": "Search name or address…",
    "index.filterAll": "All",
    "index.filterRisk": "At Risk",
    "index.filterNormal": "Normal / Safe",
    "index.loading": "Loading roster...",
    "index.noPatients": "No patients found in this category.",
    "alert.emergency": "Emergency Alert",
    "alert.type": "Event Type",
    "alert.sos": "SOS Button Pressed",
    "alert.ai": "AI Detected Fall Risk",
    "alert.hn": "HN",
    "alert.device": "Device",
    "alert.minimize": "Minimize Window",
    "alert.closeTemp": "Snooze Alert",
    "alert.details": "View Details",
    "alert.resolve": "Resolve Alert",
    "alert.minimizedTitle": "Emergency Alert (Minimized)",
    "alert.expand": "Expand Window",
    "alert.patient": "Patient",
    "alert.room": "Address",
    "alert.resolve.success": "✓ Action resolved and status reset to normal successfully.",
    "alert.resolve.failed": "Failed to resolve emergency status.",
    "lang.label.en": "English",
    "lang.label.th": "Thai",
    "patient.comm.title": "Patient Communication",
    "patient.comm.active": "Currently displaying: \"{msg}\"",
    "patient.comm.none": "No active message displaying on patient screen",
    "patient.comm.new": "Type New Message",
    "patient.comm.placeholder": "Type message to alert patient...",
    "patient.comm.send": "Send Message",
    "patient.comm.clear": "Clear Message",
    "patient.comm.presets": "Quick Presets",
    "patient.comm.confirmSend": "Confirm sending message \"{msg}\" to patient's mobile screen?",
    "patient.comm.confirmClear": "Confirm clearing the message currently on the patient's screen?",
    "patient.comm.successSend": "Alert message sent to patient screen successfully",
    "patient.comm.successClear": "Message cleared successfully",
    "patient.comm.failedSend": "Failed to send message",
    "patient.comm.failedClear": "Failed to clear message",
    "patient.comm.preset.sitdown": "⚠️ Please sit down and take a rest.",
    "patient.comm.preset.coming": "🔔 A caregiver is on the way to your room.",
    "patient.comm.preset.wristband": "⌚ Please adjust your wristband to be secure.",
    "patient.comm.sos.tooltip": "Send SOS Emergency Siren Alert",
    "patient.comm.sos.confirm": "Confirm sending SOS siren alert to patient {name}?",
    "patient.comm.sos.success": "🚨 SOS alert sent to {name}'s mobile screen successfully.",
    "patient.comm.sos.failed": "Failed to send SOS signal.",
    "patient.comm.qr.tooltip": "Show Mobile QR Code Link",
    "patient.comm.qr.title": "Share and Open on Smartphone",
    "patient.comm.qr.desc": "Scan this QR Code to open the patient mobile view.",
    "patient.comm.qr.tip": "💡 Tip: The scanning mobile phone must connect to the same Wi-Fi network as this dashboard to access the simulator.",
    "patient.comm.mobile.tooltip": "Open Patient Mobile Screen",
    "patient.details.hide": "Hide Details",
    "patient.details.show": "Show All Details",
    "patient.telemetry.sensorStatus": "Sensor Status:",
    "patient.telemetry.connected": "Connected",
    "patient.telemetry.disconnected": "Disconnected",
    "patient.telemetry.deviceId": "Device ID:",
    "patient.telemetry.noDevice": "None",
    "patient.telemetry.wearWarning": "Wristband Loose or Not Worn",
    "patient.telemetry.disconnectedDesc": "Device completely disconnected. Please check signals.",
    "patient.telemetry.looseDesc": "Wristband is loose or the patient is not wearing the device.",
    "patient.telemetry.emptyLogs": "No anomaly logs found for this patient.",
    "patient.telemetry.ageVal": "{age} years",
    "mobile.header.msgTitle": "Urgent: Message from Caregiver",
    "mobile.action.understand": "Understand",
    "mobile.action.notUnderstand": "Don't Understand",
    "mobile.state.danger": "⚠️ Danger State",
    "mobile.state.safe": "🟢 Safe State",
    "mobile.state.dangerDesc": "System detected fall and alerted caregiver.",
    "mobile.state.safeDesc": "Sensors operating normally.",
    "mobile.warning.wear": "⚠️ Wristband Disconnected / Loose",
    "mobile.warning.wearDesc": "Please adjust or wear it securely on wrist.",
    "mobile.greeting": "Hello ☀️",
    "mobile.kpi.actualFalls": "Actual Falls Today",
    "mobile.kpi.riskEvents": "Risk Events",
    "mobile.logs.title": "Recent Items",
    "mobile.logs.empty": "No falls detected by sensors today.",
    "mobile.logs.sos": "Manual SOS Pressed",
    "mobile.logs.sensorRisk": "Sensor Detected Fall",
    "mobile.profile.title": "Your General Information",
    "mobile.profile.name": "Patient Name",
    "mobile.profile.age": "Age",
    "mobile.profile.room": "Address",
    "mobile.profile.medical": "Medical History",
    "mobile.profile.medicalNone": "None",
    "mobile.profile.device": "Wearable Device ID",
    "mobile.profile.deviceNone": "Not Connected",
    "mobile.sos.help": "Help",
    "mobile.sos.cancel": "Cancel",
    "mobile.nav.home": "Home",
    "mobile.nav.logs": "Logs",
    "mobile.nav.profile": "Profile",
    "mobile.tts.listen": "Listen",
    "mobile.action.close": "Close",
    "mobile.tts.enteredHome": "Entered home screen",
    "mobile.tts.enteredLogs": "Entered fall logs history",
    "mobile.tts.enteredProfile": "Entered patient information profile",
    "mobile.tts.newMsg": "New message from caregiver: {msg}. Please select Understand or Don't Understand on the screen.",
    "mobile.tts.sensorRisk": "Warning: Sensor detected a fall risk. Caregiver has been notified.",
    "mobile.tts.cancelSos": "Emergency help request cancelled.",
    "mobile.tts.countdown": "Sending emergency signal in {sec} seconds.",
    "mobile.tts.sentSos": "Emergency signal sent successfully. Caregiver has been notified.",
    "mobile.tts.normal": "Status returned to normal.",
    "mobile.warning.wearSpeech": "Hello, your wearable device is loose or detached. Please wear it securely.",
    "mobile.warning.normalSpeech": "Hello, your wristband is secure and connected normally. If you need urgent help, please call the caregiver.",
    "mobile.warning.riskSpeech": "Warning! Sensor detected a fall. If this is a mistake, press the green I'm Safe button.",
    "mobile.summary.homeTitle": "Home Summary",
    "mobile.summary.logsTitle": "Today's Fall History Summary",
    "mobile.summary.profileTitle": "Your Personal Information Summary",
    "mobile.summary.homeItemSafe": "🟢 Health Status: Very Safe",
    "mobile.summary.homeItemNormal": "🟢 Health Status: Safe",
    "mobile.summary.homeItemRisk": "🚨 Status: Fall Detected!",
    "mobile.summary.homeActionSent": "📞 Action: Sent alert to caregiver",
    "mobile.summary.homeAdviceSafe": "💡 Advice: If safe, press green 'I'm Safe'",
    "mobile.summary.homeDeviceWarn": "⚠️ Connection: Device loose or detached",
    "mobile.summary.homeAdviceTight": "💡 Advice: Wear wristband securely",
    "mobile.summary.homeDeviceNormal": "⚡ Device: Connected and secure",
    "mobile.summary.homeWearNormal": "👤 Wear: Good skin contact",
    "mobile.summary.logsSpeech": "You are on the fall history page. Today there were {sosCount} manual SOS presses and {riskCount} automatic fall detections.",
    "mobile.summary.logsItemSos": "🔴 Manual SOS: {count} times",
    "mobile.summary.logsItemRisk": "🟡 Auto Fall Risk: {count} times",
    "mobile.summary.logsItemOverview": "🟢 Overview: Normal health status",
    "mobile.summary.profileSpeech": "Here is your personal info. Your name is {name}, age {age}, address is {room}, and medical history is {history}.",
    "mobile.summary.profileItemName": "👤 Patient: {name}",
    "mobile.summary.profileItemAge": "🎂 Age: {age} years",
    "mobile.summary.profileItemRoom": "🚪 Address: {room}",
    "mobile.summary.profileItemMedical": "💊 Medical History: {history}",
    "mobile.summary.profileItemDevice": "🆔 Device ID: {device}",
    "mobile.fontScale": "Text Size",
    "mobile.theme": "App Tone",
    "profile.settings": "Profile Settings",
    "profile.adminTitle": "Admin Profile Settings",
    "profile.updateDesc": "Update your contact details below.",
    "profile.username": "Username",
    "profile.email": "Email Address",
    "profile.phone": "Phone Number",
    "profile.signout": "Sign out",
    "dashboard.help.title": "SentinelCare Manual",
    "dashboard.help.statusTitle": "Fall Risk Status Definitions",
    "dashboard.help.riskDesc": "Acceleration/gyroscope sensors detected abnormal movement matching fall patterns.",
    "dashboard.help.normalDesc": "Telemetry and sensor values are safe. No dangerous motions detected.",
    "dashboard.help.offline": "Offline / No Device",
    "dashboard.help.offlineDesc": "Wearable device is not worn or has disconnected from the telemetry network.",
    "dashboard.help.shortcut": "Keyboard shortcuts for filtering status:",
    "dashboard.help.shortcutDesc": "on keyboard to select all, at risk, or normal status respectively.",
  },
} as const;

type TKey = keyof typeof dictionaries.en;

const th: Record<TKey, string> = {
  "app.name": "Fall Guard",
  "app.tagline": "AI ความเสี่ยงหกล้ม",
  "nav.monitoring": "การติดตาม",
  "nav.dashboard": "แดชบอร์ด",
  "nav.patients": "ผู้ป่วย",
  "nav.anomalies": "ประวัติสัญญาณผิดปกติ",
  "nav.settings": "ตั้งค่า",
  "header.search": "ค้นหาผู้ป่วย อุปกรณ์ เหตุการณ์…",
  "header.notifications": "การแจ้งเตือน",
  "header.role": "ผู้ดูแล",
  "a11y.theme": "สลับโหมดสว่าง/มืด",
  "a11y.fontSmaller": "ลดขนาดตัวอักษร",
  "a11y.fontReset": "ขนาดตัวอักษรปกติ",
  "a11y.fontLarger": "เพิ่มขนาดตัวอักษร",
  "a11y.language": "เปลี่ยนภาษา",
  "dashboard.title": "ภาพรวมทั่วไป",
  "dashboard.subtitle": "ติดตามผู้ป่วย {n} คนแบบเรียลไทม์ · อัปเดตต่อเนื่อง",
  "dashboard.managePatients": "จัดการผู้ป่วย",
  "kpi.atRisk": "ผู้ป่วยที่มีความเสี่ยง",
  "kpi.atRisk.hint": "เรียลไทม์ · ต้องการการดูแล",
  "kpi.alertsToday": "การแจ้งเตือนความเสี่ยงวันนี้",
  "kpi.alertsToday.hint": "+15% เทียบสัปดาห์ก่อน",
  "kpi.monitored": "ผู้ป่วยที่ติดตาม",
  "kpi.monitored.hint": "อาการคงที่ขึ้น 2 คน",
  "kpi.uptime": "อุปกรณ์ออนไลน์",
  "kpi.uptime.hint": "จากอุปกรณ์สวมใส่ 8 ชิ้น",
  "chart.trends.title": "แนวโน้มเหตุการณ์เสี่ยงหกล้ม",
  "chart.trends.desc": "เปรียบเทียบการเคลื่อนไหวเสี่ยงกับปกติที่ AI ทำนาย",
  "chart.byHour.title": "ความเสี่ยงตามช่วงเวลา",
  "chart.byHour.desc": "การแจ้งเตือนส่วนใหญ่กระจุกตัวช่วงกลางคืน",
  "range.daily": "รายวัน",
  "range.weekly": "รายสัปดาห์",
  "range.monthly": "รายเดือน",
  "range.yearly": "รายปี",
  "roster.title": "รายชื่อผู้ป่วย",
  "roster.desc": "สถานะสดจากอุปกรณ์สวมใส่แต่ละชิ้น",
  "patient.device": "อุปกรณ์",
  "patient.lastUpdate": "อัปเดตล่าสุด",
  "patient.monitor": "ติดตาม",
  "status.normal": "ปกติ",
  "status.risk": "ความเสี่ยงหกล้ม",
  "patients.title": "ภาพรวมผู้ป่วย",
  "patients.subtitle": "เพิ่ม แก้ไข และจัดการผู้ป่วยและอุปกรณ์ที่ติดตาม",
  "patients.add": "เพิ่มผู้ป่วย",
  "patients.edit": "แก้ไขข้อมูลผู้ป่วย",
  "patients.addNew": "เพิ่มผู้ป่วยใหม่",
  "patients.editDesc": "อัปเดตข้อมูลส่วนตัวและอุปกรณ์",
  "patients.addDesc": "ลงทะเบียนผู้ป่วยใหม่และเชื่อมต่ออุปกรณ์สวมใส่",
  "field.name": "ชื่อ-นามสกุล",
  "field.age": "อายุ",
  "field.gender": "เพศ",
  "field.weight": "น้ำหนัก (กก.)",
  "field.height": "ส่วนสูง (ซม.)",
  "field.deviceId": "รหัสอุปกรณ์",
  "field.room": "ที่อยู่",
  "gender.female": "หญิง",
  "gender.male": "ชาย",
  "action.cancel": "ยกเลิก",
  "action.save": "บันทึก",
  "action.addPatient": "เพิ่มผู้ป่วย",
  "col.patient": "ผู้ป่วย",
  "col.age": "อายุ",
  "col.gender": "เพศ",
  "col.bmi": "BMI",
  "col.device": "อุปกรณ์",
  "col.room": "ที่อยู่",
  "col.status": "สถานะ",
  "col.actions": "การจัดการ",
  "col.date": "วันที่",
  "col.time": "เวลา",
  "col.event": "ประเภทเหตุการณ์",
  "col.accel": "ความเร่ง (g)",
  "col.gyro": "ไจโร (°/วิ)",
  "col.severity": "ระดับ",
  "anomalies.title": "ประวัติสัญญาณผิดปกติ",
  "anomalies.subtitle": "เหตุการณ์ผิดปกติทั้งหมดที่ตรวจพบจากผู้ป่วยที่ติดตาม",
  "anomalies.export": "ส่งออก CSV",
  "anomalies.filters": "ตัวกรอง",
  "anomalies.filtersDesc": "ค้นหาผู้ป่วย กรองตามประเภทหรือระดับความรุนแรง",
  "anomalies.search": "ค้นหาชื่อผู้ป่วย…",
  "anomalies.allTypes": "ทุกประเภท",
  "anomalies.allSeverities": "ทุกระดับ",
  "anomalies.noResults": "ไม่พบเหตุการณ์ที่ตรงกับตัวกรอง",
  "severity.high": "สูง",
  "severity.medium": "ปานกลาง",
  "severity.low": "ต่ำ",
  "patient.back": "ผู้ป่วย",
  "patient.aiPrediction": "ผลการทำนายของ AI ปัจจุบัน",
  "patient.fallRisk": "ตรวจพบความเสี่ยงหกล้ม",
  "patient.normalActivity": "กิจกรรมปกติ",
  "patient.confidence": "ความมั่นใจ",
  "patient.model": "โมเดล",
  "patient.realtime.accel": "เซนเซอร์ความเร่ง",
  "patient.realtime.gyro": "ไจโรสโคป",
  "patient.realtime.live": "สด",
  "patient.trend.title": "แนวโน้มความเสี่ยงรายบุคคล",
  "patient.trend.desc": "เกิดเหตุการณ์เสี่ยง {n} ครั้งสัปดาห์นี้ ส่วนใหญ่ช่วงกลางคืน",
  "patient.time.night": "กลางคืน (22:00–06:00)",
  "patient.time.day": "กลางวัน",
  "patient.logs.title": "ประวัติสัญญาณผิดปกติล่าสุด",
  "patient.logs.desc": "เหตุการณ์ที่บันทึกสำหรับผู้ป่วยรายนี้",
  "lang.short.en": "EN",
  "lang.short.th": "ไทย",
  "index.searchPlaceholder": "ค้นหาชื่อ หรือที่อยู่…",
  "index.filterAll": "ทั้งหมด",
  "index.filterRisk": "ตรวจพบความเสี่ยง",
  "index.filterNormal": "ปกติ / ทั่วไป",
  "index.loading": "กำลังโหลดรายชื่อผู้ป่วย...",
  "index.noPatients": "ไม่พบข้อมูลผู้ป่วยในหมวดหมู่นี้",
  "alert.emergency": "ตรวจพบสัญญาณฉุกเฉิน",
  "alert.type": "ประเภทเหตุการณ์",
  "alert.sos": "ปุ่ม SOS สัญญาณขอความช่วยเหลือ",
  "alert.ai": "ระบบ AI ตรวจพบการหกล้มเสี่ยง",
  "alert.hn": "HN",
  "alert.device": "อุปกรณ์",
  "alert.minimize": "ย่อหน้าต่าง",
  "alert.closeTemp": "ปิดแจ้งเตือนชั่วคราว",
  "alert.details": "ดูรายละเอียด",
  "alert.resolve": "ช่วยเหลือแล้ว",
  "alert.minimizedTitle": "ตรวจพบเหตุฉุกเฉิน (ย่อไว้)",
  "alert.expand": "ขยายหน้าต่าง",
  "alert.patient": "ผู้ป่วย",
  "alert.room": "ที่อยู่",
  "alert.resolve.success": "✓ ดำเนินการช่วยเหลือและรีเซ็ตสถานะเป็นปกติสำเร็จ",
  "alert.resolve.failed": "ไม่สามารถยกเลิกสถานะฉุกเฉินได้",
  "lang.label.en": "ภาษาอังกฤษ",
  "lang.label.th": "ภาษาไทย",
  "patient.comm.title": "การสื่อสารกับผู้ป่วย",
  "patient.comm.active": "กำลังแสดงอยู่: \"{msg}\"",
  "patient.comm.none": "ไม่มีข้อความแสดงอยู่บนหน้าจอมือถือผู้ป่วยในขณะนี้",
  "patient.comm.new": "พิมพ์ข้อความใหม่",
  "patient.comm.placeholder": "พิมพ์ข้อความที่ต้องการแจ้งเตือน...",
  "patient.comm.send": "ส่งข้อความ",
  "patient.comm.clear": "ล้างข้อความ",
  "patient.comm.presets": "ข้อความด่วนแนะนำ",
  "patient.comm.confirmSend": "ยืนยันการส่งข้อความ \"{msg}\" ไปยังหน้าจอมือถือของผู้ป่วยหรือไม่?",
  "patient.comm.confirmClear": "ยืนยันการยกเลิก/ล้างข้อความที่กำลังแสดงบนหน้าจอผู้ป่วยหรือไม่?",
  "patient.comm.successSend": "ส่งข้อความเตือนไปยังหน้าจอผู้ป่วยเรียบร้อย",
  "patient.comm.successClear": "ล้างข้อความหน้าจอเรียบร้อย",
  "patient.comm.failedSend": "ส่งข้อความล้มเหลว",
  "patient.comm.failedClear": "ล้างข้อความล้มเหลว",
  "patient.comm.preset.sitdown": "⚠️ กรุณานั่งลงและพักผ่อนเพื่อความปลอดภัย",
  "patient.comm.preset.coming": "🔔 ผู้ดูแลกำลังเดินไปหาที่ห้องของคุณ",
  "patient.comm.preset.wristband": "⌚ กรุณาขยับสายรัดข้อมือให้แน่นกระชับ",
  "patient.comm.sos.tooltip": "ส่งสัญญาณฉุกเฉิน SOS",
  "patient.comm.sos.confirm": "ยืนยันการส่งสัญญาณ SOS ไซเรนแจ้งเตือนไปยังผู้ป่วย {name} หรือไม่?",
  "patient.comm.sos.success": "🚨 ส่ง SOS แจ้งเตือนไปยังหน้าจอมือถือของ {name} เรียบร้อย",
  "patient.comm.sos.failed": "ไม่สามารถส่งสัญญาณ SOS ได้",
  "patient.comm.qr.tooltip": "แสดง QR Code ลิงก์มือถือ",
  "patient.comm.qr.title": "แชร์และเปิดบนสมาร์ทโฟน",
  "patient.comm.qr.desc": "สแกน QR Code นี้เพื่อเปิดหน้าจอมือถือผู้ป่วยและตอบโต้แบบเรียลไทม์",
  "patient.comm.qr.tip": "💡 คำแนะนำ: มือถือที่ใช้สแกนจะต้องเชื่อมต่อเครือข่าย Wi-Fi วงเดียวกันกับเครื่องที่เปิดแดชบอร์ดนี้อยู่เพื่อเข้าถึงเซิร์ฟเวอร์จำลอง",
  "patient.comm.mobile.tooltip": "เปิดจอภาพฝั่งผู้ป่วย",
  "patient.details.hide": "ซ่อนรายละเอียด",
  "patient.details.show": "แสดงรายละเอียดทั้งหมด",
  "patient.telemetry.sensorStatus": "สถานะเซนเซอร์:",
  "patient.telemetry.connected": "เชื่อมต่อแล้ว",
  "patient.telemetry.disconnected": "ขาดการเชื่อมต่อ",
  "patient.telemetry.deviceId": "รหัสอุปกรณ์:",
  "patient.telemetry.noDevice": "ไม่มี",
  "patient.telemetry.wearWarning": "อุปกรณ์หลุดหรือหลวม",
  "patient.telemetry.disconnectedDesc": "อุปกรณ์ขาดการเชื่อมต่ออย่างสิ้นเชิง กรุณาเปิดเครื่องและตรวจสอบสัญญาณสัญญาณ",
  "patient.telemetry.looseDesc": "ตรวจพบว่าสายรัดข้อมือหลวม หรือผู้ป่วยไม่ได้สวมใส่อุปกรณ์ในขณะนี้",
  "patient.telemetry.emptyLogs": "ไม่พบประวัติเหตุการณ์ผิดปกติสำหรับผู้ป่วยรายนี้",
  "patient.telemetry.ageVal": "{age} ปี",
  "mobile.header.msgTitle": "ด่วน: ข้อความจากผู้ดูแล",
  "mobile.action.understand": "เข้าใจ",
  "mobile.action.notUnderstand": "ไม่เข้าใจ",
  "mobile.state.danger": "⚠️ ภาวะอันตราย",
  "mobile.state.safe": "🟢 ปลอดภัยดี",
  "mobile.state.dangerDesc": "ระบบตรวจพบล้มและส่งสัญญาณแล้ว",
  "mobile.state.safeDesc": "เซนเซอร์ทำงานปกติ",
  "mobile.warning.wear": "⚠️ อุปกรณ์สวมใส่หลุด",
  "mobile.warning.wearDesc": "โปรดขยับหรือใส่ให้กระชับข้อมือ",
  "mobile.greeting": "สวัสดีครับ ☀️",
  "mobile.kpi.actualFalls": "ล้มจริงวันนี้",
  "mobile.kpi.riskEvents": "พบความเสี่ยงล้ม",
  "mobile.logs.title": "รายการล่าสุด",
  "mobile.logs.empty": "วันนี้เซนเซอร์ไม่ตรวจพบการล้มปกติครับ",
  "mobile.logs.sos": "กด SOS เอง",
  "mobile.logs.sensorRisk": "เซนเซอร์ตรวจพบล้ม",
  "mobile.profile.title": "ข้อมูลทั่วไปของคุณ",
  "mobile.profile.name": "ชื่อผู้ป่วย",
  "mobile.profile.age": "อายุ",
  "mobile.profile.room": "ที่อยู่",
  "mobile.profile.medical": "โรคประจำตัว",
  "mobile.profile.medicalNone": "ไม่มี",
  "mobile.profile.device": "รหัสอุปกรณ์สวมใส่",
  "mobile.profile.deviceNone": "ไม่ได้เชื่อมต่อ",
  "mobile.sos.help": "ช่วยด้วย",
  "mobile.sos.cancel": "ยกเลิก",
  "mobile.nav.home": "หน้าหลัก",
  "mobile.nav.logs": "ประวัติล้ม",
  "mobile.nav.profile": "ข้อมูลฉัน",
  "mobile.tts.listen": "ฟังข้อมูล",
  "mobile.action.close": "รับทราบ / ปิด",
  "mobile.tts.enteredHome": "เข้าสู่หน้าแรกครับ",
  "mobile.tts.enteredLogs": "เข้าสู่หน้าประวัติการล้มครับ",
  "mobile.tts.enteredProfile": "เข้าสู่หน้าข้อมูลผู้ป่วยครับ",
  "mobile.tts.newMsg": "มีข้อความใหม่จากผู้ดูแลครับ ข้อความว่า {msg} กรุณากดเลือกว่า เข้าใจ หรือ ไม่เข้าใจ ครับ",
  "mobile.tts.sensorRisk": "แจ้งเตือน ตรวจพบความเสี่ยงล้มจากเซนเซอร์ของคุณครับ ระบบได้แจ้งเตือนผู้ดูแลแล้วครับ",
  "mobile.tts.cancelSos": "ยกเลิกการส่งสัญญาณขอความช่วยเหลือเรียบร้อยแล้วครับ",
  "mobile.tts.countdown": "กำลังส่งสัญญาณฉุกเฉินใน {sec} วินาทีครับ",
  "mobile.tts.sentSos": "ส่งสัญญาณฉุกเฉินเรียบร้อยแล้ว ได้ส่งข้อความแจ้งเตือนไปยังผู้ดูแลแล้วครับ",
  "mobile.tts.normal": "ยินดีด้วยครับ ระบบเข้าสู่สถานะปกติแล้วครับ",
  "mobile.warning.wearSpeech": "สวัสดีครับคุณ {name} ขณะนี้อุปกรณ์สวมใส่ของคุณสวมไม่สนิทหรือหลุดครับ สถานะทั่วไปของคุณปลอดภัยดี แต่เซนเซอร์ตรวจวัดข้อมูลไม่ได้ กรุณาใส่สายรัดข้อมือให้กระชับขึ้นนะครับ",
  "mobile.warning.normalSpeech": "สวัสดีครับคุณ {name} ขณะนี้อุปกรณ์สายรัดข้อมือเชื่อมต่อและสวมใส่ได้แนบสนิทปกติครับ สุขภาพของคุณในตอนนี้ปลอดภัยดีมากครับ หากต้องการความช่วยเหลือเร่งด่วน กรุณาโทรหาผู้ดูแลนะครับ",
  "mobile.warning.riskSpeech": "แจ้งเตือนด่วนครับ! ขณะนี้ตรวจพบสัญญาณการหกล้มจากเซนเซอร์ของคุณ และได้แจ้งเตือนผู้ดูแลแล้วครับ หากคุณปลอดภัยดี กรุณากดปุ่มสีเขียว ฉันปลอดภัย บนหน้าจอทันทีนะครับ",
  "mobile.summary.homeTitle": "สรุปข้อมูลหน้าหลัก",
  "mobile.summary.logsTitle": "สรุปประวัติการหกล้มวันนี้",
  "mobile.summary.profileTitle": "สรุปข้อมูลส่วนตัวของคุณ",
  "mobile.summary.homeItemSafe": "🟢 สถานะสุขภาพ: ปลอดภัยดีมาก",
  "mobile.summary.homeItemNormal": "🟢 สถานะสุขภาพ: ปลอดภัยดี",
  "mobile.summary.homeItemRisk": "🚨 Status: ตรวจพบการหกล้มฉุกเฉิน!",
  "mobile.summary.homeActionSent": "📞 ดำเนินการ: ส่งสัญญาณไปยังผู้ดูแลแล้ว",
  "mobile.summary.homeAdviceSafe": "💡 คำแนะนำ: หากปลอดภัยดี ให้กดปุ่มสีเขียว 'ฉันปลอดภัย'",
  "mobile.summary.homeDeviceWarn": "⚠️ การเชื่อมต่อ: อุปกรณ์หลุดหรือหลวม",
  "mobile.summary.homeAdviceTight": "💡 Advice: โปรดสวมสายรัดข้อมือให้กระชับขึ้น",
  "mobile.summary.homeDeviceNormal": "⚡ อุปกรณ์: เชื่อมต่อและสวมใส่ปกติ",
  "mobile.summary.homeWearNormal": "👤 การสวมใส่: สัมผัสผิวหนังแนบสนิทดี",
  "mobile.summary.logsSpeech": "ขณะนี้คุณอยู่ในหน้าประวัติการล้มครับ วันนี้มีการกดปุ่มฉุกเฉินเอสโอเอสเอง {sosCount} ครั้ง และระบบแจ้งเตือนความเสี่ยงล้มอัตโนมัติ {riskCount} ครั้งครับ",
  "mobile.summary.logsItemSos": "🔴 กดขอความช่วยเหลือเอง (SOS): {count} ครั้ง",
  "mobile.summary.logsItemRisk": "🟡 ตรวจพบความเสี่ยงล้มอัตโนมัติ: {count} ครั้ง",
  "mobile.summary.logsItemOverview": "🟢 ภาพรวม: สุขภาพและความเสถียรปกติ",
  "mobile.summary.profileSpeech": "นี่คือข้อมูลส่วนตัวของคุณครับ คุณชื่อคุณ {name} อายุ {age} ปี ที่อยู่คือ {room} โรคประจำตัวของคุณคือ {history} ครับ",
  "mobile.summary.profileItemName": "👤 ชื่อผู้ป่วย: คุณ{name}",
  "mobile.summary.profileItemAge": "🎂 อายุ: {age} ปี",
  "mobile.summary.profileItemRoom": "🚪 ที่อยู่: {room}",
  "mobile.summary.profileItemMedical": "💊 โรคประจำตัว: {history}",
  "mobile.summary.profileItemDevice": "🆔 อุปกรณ์: รหัส {device}",
  "mobile.fontScale": "ขนาดอักษร",
  "mobile.theme": "โทนสีแอป",
  "profile.settings": "ตั้งค่าโปรไฟล์",
  "profile.adminTitle": "ตั้งค่าโปรไฟล์ผู้ดูแลระบบ",
  "profile.updateDesc": "อัปเดตข้อมูลการติดต่อของคุณด้านล่าง",
  "profile.username": "ชื่อผู้ใช้งาน",
  "profile.email": "ที่อยู่อีเมล",
  "profile.phone": "เบอร์โทรศัพท์",
  "profile.signout": "ออกจากระบบ",
  "dashboard.help.title": "คู่มือการใช้งานระบบ",
  "dashboard.help.statusTitle": "นิยามความเสี่ยงและสถานะผู้ป่วย",
  "dashboard.help.riskDesc": "ระบบเซนเซอร์วัดค่าความเร่ง/ไจโรพบความผิดปกติที่ตรงกับรูปแบบการล้ม มีความเสี่ยงสูง",
  "dashboard.help.normalDesc": "สถิติและค่าเซนเซอร์อยู่ในเกณฑ์ปลอดภัย ไม่พบความเคลื่อนไหวที่เป็นอันตราย",
  "dashboard.help.offline": "ออฟไลน์",
  "dashboard.help.offlineDesc": "ไม่ได้สวมใส่อุปกรณ์ หรืออุปกรณ์ตัดการเชื่อมต่อกับเครือข่ายสัญญาณ",
  "dashboard.help.shortcut": "คีย์ลัดสำหรับกรองสถานะ:",
  "dashboard.help.shortcutDesc": "บนคีย์บอร์ดเพื่อเลือกสถานะทั้งหมด, มีความเสี่ยง, หรือปกติ ตามลำดับ",
};

const Ctx = createContext<Settings | null>(null);

export function SettingsProvider({ children }: { children: ReactNode }) {
  const [theme, setTheme] = useState<Theme>("light");
  const [fontScale, setFontScale] = useState(1);
  const [lang, setLang] = useState<Lang>("en");
  const [hydrated, setHydrated] = useState(false);

  useEffect(() => {
    try {
      const raw = localStorage.getItem("sc-settings");
      if (raw) {
        const s = JSON.parse(raw);
        if (s.theme === "dark" || s.theme === "light") setTheme(s.theme);
        if (typeof s.fontScale === "number") setFontScale(s.fontScale);
        if (s.lang === "en" || s.lang === "th") setLang(s.lang);
      }
    } catch {
      /* ignore */
    }
    setHydrated(true);
  }, []);

  useEffect(() => {
    if (!hydrated) return;
    try {
      localStorage.setItem(
        "sc-settings",
        JSON.stringify({ theme, fontScale, lang }),
      );
    } catch {
      /* ignore */
    }
    const html = document.documentElement;
    html.classList.toggle("dark", theme === "dark");
    html.style.fontSize = `${Math.round(fontScale * 16)}px`;
    html.lang = lang;
  }, [theme, fontScale, lang, hydrated]);

  const t = (key: TKey) => {
    const table = lang === "th" ? th : dictionaries.en;
    return (table as Record<string, string>)[key] ?? dictionaries.en[key] ?? key;
  };

  return (
    <Ctx.Provider
      value={{
        theme,
        fontScale,
        lang,
        setTheme,
        toggleTheme: () => setTheme(theme === "dark" ? "light" : "dark"),
        setFontScale,
        setLang,
        t,
      }}
    >
      {children}
    </Ctx.Provider>
  );
}

export function useSettings() {
  const v = useContext(Ctx);
  if (!v) throw new Error("SettingsProvider missing");
  return v;
}

export const useT = () => useSettings().t;
