/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProjectRouteImport } from './routes/project'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as AnomaliesRouteImport } from './routes/anomalies'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientsIndexRouteImport } from './routes/patients.index'
import { Route as PatientsIdRouteImport } from './routes/patients.$id'
import { Route as PatientsIdMobileRouteImport } from './routes/patients.$id.mobile'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectRoute = ProjectRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AnomaliesRoute = AnomaliesRouteImport.update({
  id: '/anomalies',
  path: '/anomalies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIdRoute = PatientsIdRouteImport.update({
  id: '/patients/$id',
  path: '/patients/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIdMobileRoute = PatientsIdMobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => PatientsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anomalies': typeof AnomaliesRoute
  '/notifications': typeof NotificationsRoute
  '/project': typeof ProjectRoute
  '/settings': typeof SettingsRoute
  '/patients/$id': typeof PatientsIdRouteWithChildren
  '/patients/': typeof PatientsIndexRoute
  '/patients/$id/mobile': typeof PatientsIdMobileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anomalies': typeof AnomaliesRoute
  '/notifications': typeof NotificationsRoute
  '/project': typeof ProjectRoute
  '/settings': typeof SettingsRoute
  '/patients/$id': typeof PatientsIdRouteWithChildren
  '/patients': typeof PatientsIndexRoute
  '/patients/$id/mobile': typeof PatientsIdMobileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anomalies': typeof AnomaliesRoute
  '/notifications': typeof NotificationsRoute
  '/project': typeof ProjectRoute
  '/settings': typeof SettingsRoute
  '/patients/$id': typeof PatientsIdRouteWithChildren
  '/patients/': typeof PatientsIndexRoute
  '/patients/$id/mobile': typeof PatientsIdMobileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anomalies'
    | '/notifications'
    | '/project'
    | '/settings'
    | '/patients/$id'
    | '/patients/'
    | '/patients/$id/mobile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anomalies'
    | '/notifications'
    | '/project'
    | '/settings'
    | '/patients/$id'
    | '/patients'
    | '/patients/$id/mobile'
  id:
    | '__root__'
    | '/'
    | '/anomalies'
    | '/notifications'
    | '/project'
    | '/settings'
    | '/patients/$id'
    | '/patients/'
    | '/patients/$id/mobile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnomaliesRoute: typeof AnomaliesRoute
  NotificationsRoute: typeof NotificationsRoute
  ProjectRoute: typeof ProjectRoute
  SettingsRoute: typeof SettingsRoute
  PatientsIdRoute: typeof PatientsIdRouteWithChildren
  PatientsIndexRoute: typeof PatientsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project': {
      id: '/project'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof ProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anomalies': {
      id: '/anomalies'
      path: '/anomalies'
      fullPath: '/anomalies'
      preLoaderRoute: typeof AnomaliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/': {
      id: '/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$id': {
      id: '/patients/$id'
      path: '/patients/$id'
      fullPath: '/patients/$id'
      preLoaderRoute: typeof PatientsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$id/mobile': {
      id: '/patients/$id/mobile'
      path: '/mobile'
      fullPath: '/patients/$id/mobile'
      preLoaderRoute: typeof PatientsIdMobileRouteImport
      parentRoute: typeof PatientsIdRoute
    }
  }
}

interface PatientsIdRouteChildren {
  PatientsIdMobileRoute: typeof PatientsIdMobileRoute
}

const PatientsIdRouteChildren: PatientsIdRouteChildren = {
  PatientsIdMobileRoute: PatientsIdMobileRoute,
}

const PatientsIdRouteWithChildren = PatientsIdRoute._addFileChildren(
  PatientsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnomaliesRoute: AnomaliesRoute,
  NotificationsRoute: NotificationsRoute,
  ProjectRoute: ProjectRoute,
  SettingsRoute: SettingsRoute,
  PatientsIdRoute: PatientsIdRouteWithChildren,
  PatientsIndexRoute: PatientsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
